# -*- coding: utf-8 -*-

{
    'name': 'NSTDA :: PABI2 - Forms',
    'version': '8.0.1.0.0',
    'author': 'Ecosoft',
    'website': 'http://ecosoft.co.th',
    'depends': [
        'jasper_reports',
        'hr',
        'l10n_th_amount_text_ext',
        'l10n_th_fields',
        'pabi_account',
        'purchase_invoice_line_percentage',
        'purchase_invoice_plan',
        'account',
        'pabi_asset_management',
        'pabi_hr_salary',
        'report_custom_filename',
        'report_qweb_element_page_visibility',
    ],
    'data': [
        'data/report_paperformat_data.xml',
        'data/procurement_data.xml',
        'data/account_data.xml',
        'data/payment_export_data.xml',
        'data/asset_data.xml',
        'data/hr_salary_data.xml',
        'data/cheque_data.xml',
        'qweb_reports/account/layouts.xml',
        'qweb_reports/account/adjustment_voucher.xml',
        'qweb_reports/account/bank_receipt_voucher.xml',
        'qweb_reports/account/invoice_voucher.xml',
        'qweb_reports/account/payment_voucher.xml',
        'qweb_reports/account/receipt_voucher.xml',
        'qweb_reports/account/salary_expense_voucher.xml',
        'qweb_reports/account/interface_account_voucher.xml',
        'qweb_reports/account/employee_expense_voucher.xml',
        'qweb_reports/account/delivery_order_voucher.xml',
        'print_journal_entries/print_voucher_wizard.xml',
        'print_payment_export/print_payment_export_wizard.xml',
        'print_account_invoice/print_account_invoice_wizard.xml',
        'print_account_voucher/print_account_voucher_wizard.xml',
        'print_payment_cheque/print_payment_cheque_wizard.xml',
        'views/account_voucher_view.xml',
    ],
    'installable': True,
    'auto_install': False,
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
