# -*- coding: utf-8 -*-
from . import stock_account
from . import asset
from . import asset_purchase_method
from . import asset_transfer
from . import asset_changeowner
from . import asset_request
from . import asset_removal
from . import asset_adjust
from . import asset_location
from . import product
from . import purchase_requisition
from . import account_invoice
from . import account_move
from . import stock
from . import account
from . import purchase
from . import res_project
from . import res_section
from . import hr_expense
